npm install gitbook-plugin-simple-page-toc
npm install gitbook-plugin-anchor-navigation-ex
npm install gitbook-plugin-copy-code-button
npm install gitbook-plugin-tbfed-pagefooter
npm install gitbook-plugin-search-plus
npm install gitbook-plugin-emphasize
npm install gitbook-plugin-katex
npm install gitbook-plugin-todo
npm install gitbook-plugin-prism
npm install gitbook-plugin-prism-themes
npm install gitbook-plugin-custom-favicon